- hosts: all
  become: yes
  tasks:
#   - name: Adding Docker Repository
#     yum_repository:
#       name: docker-ce
#       description: Docker repository
#       baseurl: https://download.docker.com/linux/centos/docker-ce.repo

   - name: install Docker
     yum:
       name: docker-ce
       state: present
       update_cache: true

   - name: start Docker
     service:
       name: docker
       state: started

#   - name: disable SELinux
#     command: setenforce 0

#   - name: disable SELinux on reboot
#     selinux:
#       state: disabled

   - name: ensure net.bridge.bridge-nf-call-ip6tables is set to 1
     sysctl:
      name: net.bridge.bridge-nf-call-ip6tables
      value: 1
      state: present

   - name: ensure net.bridge.bridge-nf-call-iptables is set to 1
     sysctl:
      name: net.bridge.bridge-nf-call-iptables
      value: 1
      state: present

   - name: add Kubernetes' YUM repository
     yum_repository:
      name: Kubernetes
      description: Kubernetes YUM repository
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      gpgcheck: yes

   - name: install kubelet and Kubeadm
     yum:
        name: kubelet-1.14.0
        state: present
        update_cache: true
     loop: ['kubelet-1.14.0', 'kubeadm-1.14.0']

   - name: start kubelet
     service:
       name: kubelet
       enabled: yes
       state: started

   - name: Installing Python3
     yum: 
       name: "{{ item }}"
       state: present
     loop: ['python3-setuptools', 'python3-pip']

   - name: Installing Python docker modules
     pip:
       name: "{{ item }}"
     loop: ['docker-py', 'lxml']

- hosts: master
  become: yes
  tasks:
   - name: install kubectl
     yum:
        name: kubectl-1.14.0
        state: present
        allow_downgrade: yes
