---
- hosts: Deploy
  become: true
  tasks:
    - name: Getting Information
      shell: "date +%Y-%m-%d"
      register: tstamp

    - name: Setting naming information
      set_fact:
        cur_date: "{{ tstamp.stdout[0:] }}"

#    - name: Installing aptitude using apt
#     apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

#    - name: Installing required system packages
#      apt: name={{ item }} state=latest update_cache=yes
#      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

#    - name: Adding Docker GPG apt Key
#      apt_key:
#        url: https://download.docker.com/linux/ubuntu/gpg
#        state: present

#    - name: Adding Docker Repository
#      apt_repository:
#        repo: deb https://download.docker.com/linux/ubuntu xenial stable
#        state: present

#    - name: Updating apt and installing docker-ce
#      apt: update_cache=yes name=docker-ce state=latest
   
#    - name: Installing modules for python
#      pip: 
#        name: {{ item }}
#      loop:[ 'docker', 'lxml']

    - name: Pulling from Nexus
      maven_artifact:
        group_id: gov.epic
        artifact_id: epic-app1
        version: latest
        extension: war
        repository_url: 'http://int-nexus.dev.int:8081/repository/maven-releases/'
        username: ******
        password: ***************
        dest: /root/

    - name: Copying Dockerfile
      copy:
        src: /Dockerfile
        dest: /root/Dockerfile

    - name: Copying setenv
      copy:
        src: /setenv.sh
        dest: /root/setenv.sh

    - name: Building Docker image
      shell: "docker build -t epic-app1 ."

    - name: Creating Container
      docker_container:
        name: Epic-app1_container_{{ cur_date }}
        image: epic-app1
        state: present
