---
- hosts: master_nodes
  become: yes
  gather_facts: false
  tasks: 
  - name: get join command
    shell: kubeadm token create --print-join-command
    register: join_command_raw

  - name: set join command
    set_fact:
      join_command: "{{ join_command_raw.stdout_lines[0] }}" 


- hosts: worker_nodes
  become: yes
  vars_files:
  - env_variables
  tasks:

  - name: Getting Ready
    shell: "rm /etc/kubernetes/pki/ca.crt"
    ignore_errors: True

  - name: Joining
    shell: "{{ hostvars['master'].join_command }}--ignore-preflight-errors all"
    ignore_errors: True

- hosts: master_nodes
  become: yes
  gather_facts: false
  tasks:  
  - name: Deploy image
    shell: kubectl run my-app --image=ubuntu:latest --port=3000
