---
- hosts: all
  become: yes
  vars_files:
  - env_variables
  tasks:
  - name: Creating a repository file for Kubernetes
    file:
     path: /etc/yum.repos.d/kubernetes.repo
     state: touch

  - name: Adding repository details in Kubernetes repo file.
    blockinfile:
     path: /etc/yum.repos.d/kubernetes.repo
     block: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
        https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

  - name: Adding Docker repository
    yum_repository:
      name: docker-ce
      description: Docker repo
      baseurl: https://download.docker.com/linux/centos/docker-ce.repo

  - name: Installing Docker
    yum:
     name: docker-ce
     state: present

  - name: Installing required packages
    yum:
     name: "{{ packages }}"
     state: present

  - name: Starting and Enabling the required services
    service:
     name: "{{ item }}"
     state: started
     enabled: yes
    with_items: "{{ services }}"
